services:
  react-app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app
      - /home/app/node_modules
      - /home/app/.next # Asegura que el build persista
    environment:
      - NODE_ENV=production
    command: ["npm", "start"]
